name: Status
on:
  push:
    branches:
      - main
      - 'release**'
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches:
      - main
      - 'release**'
    paths-ignore:
      - 'docs/**'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:

  if_error_or_failure:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for 60 seconds
        shell: bash -l {0}
        run: sleep 60s
      - env:
          DESCRIPTION: ${{ github.event.description }}
          STATUS: ${{ github.event.state }}
        run: |
          echo The event description is: $DESCRIPTION
          echo The status is: $STATUS
          if [[ $STATUS == 'error' || $STATUS == 'failure' ]]; then exit 0; else exit 1;
